### ISSUE TITLE
Codeline source_dir error

### ISSUE THREAD

**Issue by bob-rietveld** [alestic/aws-git-backed-static-website#8]
Hi, 

I have been using your setup without any problems. However recently I received this error when I pushed a commit. It seems the codepipeline source_dir is not transferred correctly (see error below). I didn't change anything (I think), any help on resolving the issue would be greatly appreciated. 

Best,

Bob

<img width="1053" alt="schermafbeelding 2017-03-08 om 10 10 04" src="https://cloud.githubusercontent.com/assets/10638517/23697273/711be23a-03e7-11e7-8a38-a6c83536e50e.png">

**Comment by ehammond** [comment]
Bob:

Thanks for reporting this. Are you using the latest code?

It is possible to upload the latest ZIP file from S3 to your AWS Lambda function in place without replacing the CloudFormation stack.

Are you saying that it was working and then it stopped working without you making any changes to the AWS Lambda functions or CloudFormation stack?

**Comment by bob-rietveld** [comment]
I deleted the stack and used the latest version, the error has gone. Thanks for your help.
